
create table research.`T_EMPLOYEE`(
`EMP_ID` VARCHAR(35) NOT NULL,
`EMP_NAME` VARCHAR(100) NOT NULL,	
`EMP_DESIGN` VARCHAR(100) NOT NULL,
`EMP_DEPT` VARCHAR(100) NOT NULL,
`EMP_ADDRESS` VARCHAR(100) DEFAULT NULL,
`EMP_STATUS` VARCHAR(1) NOT NULL,
PRIMARY KEY (`EMP_ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;